name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]   # rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build de la imagen
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nexus-battles:latest .

      # 4. Push a Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nexus-battles:latest
