# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TheNexusBattleIV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: index.docker.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_DCEE6E2BF04542E5B4EE23104663D577 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_3D37168968C64FD48C1DA70BD04C4AFE }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_DCEE6E2BF04542E5B4EE23104663D577 }}/andrespico/nexus-battles:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1FC3D9F921BC49C9A33B393D5372323C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6BE9A0B31BA14900BBEEE71A79A6F72E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_167BAB44C0A4467D88AE4AE13DABC75D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TheNexusBattleIV'
          slot-name: 'Production'
          images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_DCEE6E2BF04542E5B4EE23104663D577 }}/andrespico/nexus-battles:${{ github.sha }}'
          